name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Add .nojekyll file
        run: touch out/.nojekyll
        
      - name: Fix asset paths
        run: |
          cd out
          find . -type f -name "*.html" -exec sed -i 's/"\/_next/"\.\/_next/g' {} +
          find . -type f -name "*.js" -exec sed -i 's/"\/_next/"\.\/_next/g' {} +

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out